# path to oh-my-zsh installation
export ZSH="/Users/thomas/.oh-my-zsh"

ZSH_THEME="thowue"

plugins=(
  git
  rails
  brew
  osx
  gem
)

source $ZSH/oh-my-zsh.sh


# --- shell ---
alias mv="mv -i -v"
alias cp="cp -i -v"
alias lar="ls -lArt"
alias l="ls -1A"
alias ln="ln -sv"
alias lq="tree -a -L 3 -I '.git|*org.eclipse*'"
alias findregex="find . -iregex"
alias restart="exec $SHELL"
alias type="type -a"
alias lest="less +G"
alias sortenv="sort -o .env .env"
alias grep="grep --ignore-case --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}"
alias grepc="grep --context"

function setenv() {
  set -a
  source .env
  set +a

  if [[ $HEROKU_PG_DB ]]; then
    export DATABASE_URL="$(heroku config:get DATABASE_URL)"
  fi
}

function show() {
  la | grep $1
}

function search() {
  local keyword="*$1*"
  find . -iname $keyword
}

function search-rm() {
  local keyword="*$1*"
  find . -iname $keyword -delete
}

function search-bin() {
  echo '/usr/local/bin:'
  ls -lAh /usr/local/bin | grep $1
  echo '/usr/bin:'
  ls -lAh /usr/bin | grep $1
  echo '/bin:'
  ls -lAh /bin | grep $1
}

export LSCOLORS="Fxfxcxdxbxegedabagacad"
export LS_COLORS="di=1;35:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"
export LESS=" --RAW-CONTROL-CHARS --ignore-case "
export GREP_COLOR="0;34"

# disable START/STOP output control
stty -ixon


# --- config lists ---
alias apmlist="apm list --installed --bare > ~/coding/dotfiles/atom/apm_list.txt"
alias brewlist="brew list --versions > ~/coding/dotfiles/cellar/brew_list.txt"
alias codelist="code --list-extensions --show-versions > ~/coding/dotfiles/vscode/extensionList.txt"


# --- git ---
alias gl="git log"
alias gdh="git diff HEAD --stat --patch"
alias gdhs="git diff HEAD --staged --stat --patch"
alias gfv="git fetch --verbose"
alias gfa="git fetch --all --prune --jobs=10 --verbose"
alias gls="git log --stat"
alias glg="git log --all --decorate --oneline --graph"
alias gs="git stash"
alias gro="git remote show origin"
alias gph="git push heroku"

unalias grs
unalias grss

function grs() {
  if [[ -z $@ ]]; then
    git restore :/
  else
    git restore $@
  fi
}

function grss() {
  if [[ -z $@ ]]; then
    git restore --staged :/
  else
    git restore --staged $@
  fi
}

# remove homebrew git completion
rm /usr/local/share/zsh/site-functions/_git 2> /dev/null


# --- db ---
alias mst="mysql.server status"
alias msr="mysql.server start"
alias msp="mysql.server stop"

alias pgc="pg_ctl"
alias pst="pg_ctl status"
alias psr="pg_ctl start"
alias psp="pg_ctl stop"

function psql-heroku() {
  local DATABASE_URL="$(heroku config:get DATABASE_URL)"
  if [[ $DATABASE_URL == postgres://* ]]; then
    psql $DATABASE_URL
  else
    echo "failed to retrieve heroku DATABASE_URL config var"
  fi
}

export PGDATA="/usr/local/var/postgres"


# --- sfdx ---
alias sfdxallmd="sfdx force:source:retrieve -x ~/coding/salesforce/package.xml --verbose"
alias sfdxcode="sfdx force:source:retrieve -x ~/coding/salesforce/apex.xml --verbose"


# --- misc ---
alias -g icloud="/Users/thomas/Library/Mobile\ Documents/com~apple~CloudDocs"
alias at="atom ."
alias youtube-dl-mp3="youtube-dl --format 'bestaudio/best' --extract-audio --audio-format mp3 --embed-thumbnail"
alias hlt="heroku logs --tail"
alias rt="rails test"
alias gemi="gem install *.gem"

function init-repo() {
  mkdir "$1"
  cd "$1"
  git init
  touch .env
  echo '.env' > .gitignore
  git add .gitignore
  git commit -m 'init repo'
}

export LOGS_DIR="/Users/thomas/coding/logs"
export ARCHIVE_DIR="/Users/thomas/coding/archive"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export VISUAL=vim
export EDITOR=$VISUAL

eval "$(rbenv init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"


# --- keybindings ---
bindkey '^j' backward-word
bindkey '^l' forward-word
